; /etc/asterisk/extensions.conf
[globals]

[default]

[frontporch-diagnostics]
exten => 100,1,Answer()
 same => n,Echo()
 same => n,Hangup()

#tryinclude extensions_voipms.conf
#include conf.d/extensions_frontporch.conf
