# Generated by Django 5.2.15 on 2026-06-27 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('normalized_number', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'ordering': ['normalized_number'],
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'families',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='directory.family')),
            ],
            options={
                'ordering': ['family__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FamilyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('external_phone_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='family_contacts', to='directory.externalphonenumber')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='directory.family')),
            ],
            options={
                'ordering': ['family__name', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('is_guardian', models.BooleanField(default=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='directory.family')),
            ],
            options={
                'ordering': ['family__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('friendly_name', models.CharField(max_length=200)),
                ('sip_extension', models.CharField(max_length=32, unique=True)),
                ('sip_username', models.CharField(max_length=100, unique=True)),
                ('sip_secret', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='directory.child')),
                ('assigned_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='directory.family')),
                ('assigned_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='directory.parent')),
            ],
            options={
                'ordering': ['friendly_name'],
            },
        ),
        migrations.CreateModel(
            name='ConferenceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('members', models.ManyToManyField(related_name='conference_groups', to='directory.child')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_conference_groups', to='directory.parent')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AllowedExternalCaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_external_callers', to='directory.child')),
                ('external_phone_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allowed_child_recipients', to='directory.externalphonenumber')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_external_callers', to='directory.parent')),
            ],
            options={
                'ordering': ['child__family__name', 'child__name', 'external_phone_number'],
            },
        ),
        migrations.CreateModel(
            name='AllowedChildFamilyRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_family_relationships', to='directory.child')),
                ('target_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_child_relationships', to='directory.family')),
                ('approved_by_child_family_guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_child_family_relationships', to='directory.parent')),
                ('approved_by_target_family_guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_target_family_relationships', to='directory.parent')),
            ],
            options={
                'ordering': ['child__family__name', 'child__name', 'target_family__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='child',
            constraint=models.UniqueConstraint(fields=('family', 'name'), name='unique_child_name_per_family'),
        ),
        migrations.AddConstraint(
            model_name='familycontact',
            constraint=models.UniqueConstraint(fields=('family', 'external_phone_number'), name='unique_contact_number_per_family'),
        ),
        migrations.AddConstraint(
            model_name='parent',
            constraint=models.UniqueConstraint(fields=('family', 'name'), name='unique_parent_name_per_family'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assigned_child__isnull', False), ('assigned_parent__isnull', True), ('assigned_family__isnull', True)), models.Q(('assigned_child__isnull', True), ('assigned_parent__isnull', False), ('assigned_family__isnull', True)), models.Q(('assigned_child__isnull', True), ('assigned_parent__isnull', True), ('assigned_family__isnull', False)), _connector='OR'), name='device_has_exactly_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='allowedexternalcaller',
            constraint=models.UniqueConstraint(fields=('child', 'external_phone_number'), name='unique_allowed_external_caller_per_child'),
        ),
        migrations.AddConstraint(
            model_name='allowedchildfamilyrelationship',
            constraint=models.UniqueConstraint(fields=('child', 'target_family'), name='unique_child_family_relationship'),
        ),
    ]
