# Generated by Django 5.2.15 on 2026-06-28 19:36

import django.db.models.deletion
from django.db import migrations, models


def create_shared_frontporch_did(apps, schema_editor):
    PublicPhoneNumber = apps.get_model("directory", "PublicPhoneNumber")
    PublicPhoneNumber.objects.get_or_create(
        normalized_number="+12025550199",
        defaults={
            "label": "Example shared FrontPorch DID",
            "provider_name": "Example SIP provider",
            "is_active": False,
            "notes": "Example public number for local development only.",
        },
    )


def remove_shared_frontporch_did(apps, schema_editor):
    PublicPhoneNumber = apps.get_model("directory", "PublicPhoneNumber")
    PublicPhoneNumber.objects.filter(
        normalized_number="+12025550199",
        label="Example shared FrontPorch DID",
        assigned_family__isnull=True,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_rename_parent_name_to_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('normalized_number', models.CharField(max_length=32, unique=True)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('provider_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_family', models.ForeignKey(blank=True, help_text='Leave blank for a shared neighborhood number.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='public_phone_numbers', to='directory.family')),
            ],
            options={
                'ordering': ['normalized_number'],
            },
        ),
        migrations.RunPython(
            create_shared_frontporch_did,
            reverse_code=remove_shared_frontporch_did,
        ),
    ]
