# Generated by Django 5.2.15 on 2026-06-28 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_publicphonenumber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllowedExternalCaller',
            new_name='ExternalContactPermission',
        ),
        migrations.AlterModelOptions(
            name='externalcontactpermission',
            options={'ordering': ['child__family__name', 'child__name', 'external_phone_number']},
        ),
        migrations.AlterField(
            model_name='externalcontactpermission',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_external_contact_permissions', to='directory.parent'),
        ),
        migrations.AlterField(
            model_name='externalcontactpermission',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_contact_permissions', to='directory.child'),
        ),
        migrations.AlterField(
            model_name='externalcontactpermission',
            name='external_phone_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='child_contact_permissions', to='directory.externalphonenumber'),
        ),
        migrations.RemoveConstraint(
            model_name='externalcontactpermission',
            name='unique_allowed_external_caller_per_child',
        ),
        migrations.CreateModel(
            name='ExternalNumberExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dial_extension', models.CharField(blank=True, max_length=4, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('external_phone_number', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dialable_extension', to='directory.externalphonenumber')),
            ],
            options={
                'ordering': ['dial_extension'],
            },
        ),
        migrations.CreateModel(
            name='DialShortcut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('digits', models.CharField(max_length=1)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_dial_shortcuts', to='directory.parent')),
                ('internal_target_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_by_shortcuts', to='directory.device')),
                ('source_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dial_shortcuts', to='directory.device')),
                ('external_target_extension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_by_shortcuts', to='directory.externalnumberextension')),
            ],
            options={
                'ordering': ['source_device__friendly_name', 'digits'],
            },
        ),
        migrations.AddConstraint(
            model_name='externalcontactpermission',
            constraint=models.UniqueConstraint(fields=('child', 'external_phone_number'), name='unique_external_contact_permission_per_child'),
        ),
        migrations.AddConstraint(
            model_name='dialshortcut',
            constraint=models.UniqueConstraint(fields=('source_device', 'digits'), name='unique_shortcut_digits_per_source_device'),
        ),
        migrations.AddConstraint(
            model_name='dialshortcut',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('internal_target_device__isnull', False), ('external_target_extension__isnull', True)), models.Q(('internal_target_device__isnull', True), ('external_target_extension__isnull', False)), _connector='OR'), name='dial_shortcut_has_exactly_one_target'),
        ),
    ]
