# Generated by Codex on 2026-07-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0004_externalcontactpermission_externalnumberextension_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChildBlackoutPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=200)),
                (
                    "day_group",
                    models.CharField(
                        choices=[
                            ("weekdays", "Weekdays"),
                            ("weekends", "Weekends"),
                            ("every_day", "Every day"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_child_blackout_periods",
                        to="directory.parent",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blackout_periods",
                        to="directory.child",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "child__family__name",
                    "child__name",
                    "day_group",
                    "start_time",
                ],
            },
        ),
    ]
