# Generated by Codex on 2026-07-05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("directory", "0005_childblackoutperiod"),
    ]

    operations = [
        migrations.AddField(
            model_name="parent",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="frontporch_parent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
