# Generated by Django 5.2.15 on 2026-07-06 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_parent_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dialshortcut',
            name='dial_shortcut_has_exactly_one_target',
        ),
        migrations.AddField(
            model_name='dialshortcut',
            name='parent_phone_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_targeted_by_shortcuts', to='directory.parent'),
        ),
        migrations.AddConstraint(
            model_name='dialshortcut',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('internal_target_device__isnull', False), ('external_target_extension__isnull', True), ('parent_phone_target__isnull', True)), models.Q(('internal_target_device__isnull', True), ('external_target_extension__isnull', False), ('parent_phone_target__isnull', True)), models.Q(('internal_target_device__isnull', True), ('external_target_extension__isnull', True), ('parent_phone_target__isnull', False)), _connector='OR'), name='dial_shortcut_has_exactly_one_target'),
        ),
    ]
