# Generated by Django 5.2.15 on 2026-07-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0007_remove_dialshortcut_dial_shortcut_has_exactly_one_target_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChildLandline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("dial_extension", models.CharField(blank=True, max_length=4, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_child_landlines",
                        to="directory.parent",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="landlines",
                        to="directory.child",
                    ),
                ),
                (
                    "external_phone_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="child_landlines",
                        to="directory.externalphonenumber",
                    ),
                ),
            ],
            options={
                "ordering": ["child__family__name", "child__name", "dial_extension"],
            },
        ),
        migrations.AddConstraint(
            model_name="childlandline",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("child",),
                name="unique_active_landline_per_child",
            ),
        ),
        migrations.AddConstraint(
            model_name="childlandline",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("external_phone_number",),
                name="unique_active_child_landline_number",
            ),
        ),
    ]
