# Generated by Codex on 2026-07-11

from django.db import migrations


def create_family_contact_extensions(apps, schema_editor):
    FamilyContact = apps.get_model("directory", "FamilyContact")
    ExternalNumberExtension = apps.get_model("directory", "ExternalNumberExtension")
    Device = apps.get_model("directory", "Device")
    ChildLandline = apps.get_model("directory", "ChildLandline")

    used_extensions = set(
        ExternalNumberExtension.objects.exclude(dial_extension="").values_list(
            "dial_extension", flat=True
        )
    )
    used_extensions.update(
        Device.objects.exclude(sip_extension="").values_list("sip_extension", flat=True)
    )
    used_extensions.update(
        ChildLandline.objects.filter(is_active=True)
        .exclude(dial_extension="")
        .values_list("dial_extension", flat=True)
    )
    reserved_extensions = {"100", "911", "2", "3", "4", "5", "6", "7", "8", "9"}

    def next_extension():
        for candidate in range(1000, 10000):
            extension = str(candidate)
            if extension in reserved_extensions or extension in used_extensions:
                continue
            used_extensions.add(extension)
            return extension
        raise RuntimeError("Could not assign an unused external number extension.")

    for contact in FamilyContact.objects.order_by("id"):
        if ExternalNumberExtension.objects.filter(
            external_phone_number_id=contact.external_phone_number_id
        ).exists():
            continue
        ExternalNumberExtension.objects.create(
            external_phone_number_id=contact.external_phone_number_id,
            dial_extension=next_extension(),
            is_active=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0009_remove_dialshortcut_dial_shortcut_has_exactly_one_target_and_more"),
    ]

    operations = [
        migrations.RunPython(create_family_contact_extensions, migrations.RunPython.noop),
    ]
